# Generated by Django 4.1.1 on 2022-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='noOfLikes',
            field=models.IntegerField(default=0),
        ),
    ]
